[project]
name = "04-build-django-coding-agent"
version = "0.1.0"
description = "Building a coding agent with Django and OpenAI"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=5.2.4",
    "jupyter>=1.1.1",
    "openai>=2.14.0",
    "python-dotenv>=1.2.1",
    "toyaikit>=0.0.9",
]
