# Generated by Django 5.2.9 on 2026-01-02 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, help_text="Quantity of pets ordered"),
                ),
                (
                    "ship_date",
                    models.DateTimeField(blank=True, help_text="Expected shipping date", null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("placed", "Placed"),
                            ("approved", "Approved"),
                            ("delivered", "Delivered"),
                        ],
                        default="placed",
                        help_text="Order status",
                        max_length=20,
                    ),
                ),
                (
                    "complete",
                    models.BooleanField(default=False, help_text="Whether the order is complete"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pet",
                    models.ForeignKey(
                        help_text="Pet being ordered",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="pets.pet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
                "db_table": "orders",
                "ordering": ["-created_at"],
            },
        ),
    ]
